/**
 * TRO-557: worktree.sh must stamp the provisioning session into the worktree
 * and refuse a cross-session reuse instead of silently resetting a database
 * another session may still be using.
 *
 * The defect this guards against: two orchestrator sessions provisioned the
 * same ticket within 60 seconds (live collision, 2026-08-13). worktree.sh
 * keyed reuse purely on the ticket slug, printed one easily-missed "already
 * exists, reusing it" line, kept the FIRST session's branch checkout, and
 * DROPPED the first session's database out from under it. Both sessions then
 * worked in one worktree until ownership was reconstructed by hand from
 * stat/reflog evidence.
 *
 * This runs the real script end to end -- against a disposable git repo and
 * a disposable database on the SAME running Postgres server this test run's
 * own DATABASE_URL points at -- instead of mocking the session-id lookup
 * away, per the ticket's own instruction to exercise the mechanism directly.
 * $CLAUDE_CODE_SESSION_ID is that mechanism (see worktree.sh's own "caller
 * identity" comment); each call below sets it explicitly to a fixed test
 * value, standing in for two different real Claude Code sessions.
 */
import { execFileSync, spawnSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { Client } from "pg";
import { describe, expect, it } from "vitest";

const WORKTREE_SH = fileURLToPath(new URL("./worktree.sh", import.meta.url));

interface PgTarget {
  container: string;
  host: string;
  port: string;
  user: string;
  password: string;
}

/** Reads the Postgres connection this test run already has, via DATABASE_URL
 * (CLAUDE.md: never run with it unset). The disposable fixture database this
 * test creates lives on the SAME server, under a different name. */
function requirePgTargetFromEnv(): Omit<PgTarget, "container"> {
  const raw = process.env.DATABASE_URL;
  if (!raw) {
    throw new Error("DATABASE_URL is not set. Source .factory-env before running tests.");
  }
  const url = new URL(raw);
  return {
    host: url.hostname,
    port: url.port || "5432",
    user: decodeURIComponent(url.username),
    password: decodeURIComponent(url.password),
  };
}

/** worktree.sh's own precondition (section 1) requires a docker container by
 * NAME. Discover the real one publishing this port instead of assuming
 * "labelhunter-pg" -- CI's postgres service container has a different,
 * autogenerated name on the same runner. */
function discoverPgContainer(port: string): string {
  const result = spawnSync("docker", ["ps", "--filter", `publish=${port}`, "--format", "{{.Names}}"], {
    encoding: "utf8",
  });
  if (result.error || result.status !== 0) {
    throw new Error(
      `could not list docker containers publishing port ${port}: ${result.error?.message ?? result.stderr}`,
    );
  }
  const name = result.stdout
    .split("\n")
    .map((line) => line.trim())
    .find(Boolean);
  if (!name) {
    throw new Error(
      `no docker container publishes port ${port}. worktree.sh's own container-presence check needs one.`,
    );
  }
  return name;
}

function uniqueTicket(): string {
  // Matches worktree.sh's own ^[A-Za-z][A-Za-z0-9]*-[A-Za-z0-9]+$ validation.
  // randomUUID, not Date.now()+pid: two runners can share a pid and still
  // start within the same millisecond, and a shared ticket id races two
  // test runs onto the same fixture database. (CodeRabbit, this PR.)
  const raw = randomUUID().replace(/-/g, "").toUpperCase();
  return `ZZOWN${raw.slice(0, 12)}-1`;
}

/** worktree.sh's own transform: `tr '[:upper:]-' '[:lower:]_'`. */
function ticketSlug(ticket: string): string {
  return ticket.toLowerCase().replace(/-/g, "_");
}

interface Fixture {
  scratchRoot: string;
  repoDir: string;
  worktreeDir: string;
  dbName: string;
  ticket: string;
  branch: string;
}

/** Runs a git command in the scratch repo, using an explicit test identity. */
function scratchGit(cwd: string, args: string[]): string {
  return execFileSync("git", args, { cwd, encoding: "utf8" }).trim();
}

function makeFixture(): Fixture {
  const ticket = uniqueTicket();
  const slug = ticketSlug(ticket);
  const scratchRoot = mkdtempSync(join(tmpdir(), "lh-wt-owner-"));
  const repoDir = join(scratchRoot, "repo");
  execFileSync("git", ["init", "-q", "-b", "main", repoDir]);
  scratchGit(repoDir, ["config", "user.email", "tro-557-test@example.com"]);
  scratchGit(repoDir, ["config", "user.name", "TRO-557 test"]);
  writeFileSync(join(repoDir, "README.md"), "TRO-557 disposable test fixture\n");
  scratchGit(repoDir, ["add", "README.md"]);
  scratchGit(repoDir, ["commit", "-q", "-m", "init"]);
  return {
    scratchRoot,
    repoDir,
    worktreeDir: join(scratchRoot, `labelhunter-wt-${slug}`),
    dbName: `labelhunter_wt_${slug}`,
    ticket,
    branch: `test/tro-557-${slug}`,
  };
}

function runWorktreeSh(fx: Fixture, pg: PgTarget, sessionId: string, extraArgs: string[] = []) {
  const env: NodeJS.ProcessEnv = { ...process.env };
  // Isolate the mechanism under test: no override, and a session id this
  // test controls, standing in for a real Claude Code session's own
  // $CLAUDE_CODE_SESSION_ID.
  delete env.FACTORY_SESSION_ID;
  env.CLAUDE_CODE_SESSION_ID = sessionId;
  env.FACTORY_PG_CONTAINER = pg.container;
  env.FACTORY_PG_HOST = pg.host;
  env.FACTORY_PG_PORT = pg.port;
  env.FACTORY_PG_USER = pg.user;
  env.FACTORY_PG_PASSWORD = pg.password;
  return spawnSync(WORKTREE_SH, [fx.ticket, fx.branch, "main", ...extraArgs], {
    cwd: fx.repoDir,
    env,
    encoding: "utf8",
  });
}

async function queryDb(pg: PgTarget, dbName: string, sql: string) {
  const client = new Client({
    host: pg.host,
    port: Number(pg.port),
    user: pg.user,
    password: pg.password,
    database: dbName,
    connectionTimeoutMillis: 10_000,
    query_timeout: 10_000,
  });
  await client.connect();
  try {
    return await client.query(sql);
  } finally {
    await client.end();
  }
}

/** Every step runs even if an earlier one throws (lessons.md #24). On
 * failure this both logs (so the cause is visible even if the throw below
 * gets swallowed by `withFixture`) and throws an AggregateError, so a
 * cleanup-only failure fails the test instead of passing silently. */
async function cleanupFixture(fx: Fixture, pg: PgTarget): Promise<void> {
  const errors: unknown[] = [];
  try {
    execFileSync("git", ["worktree", "remove", "--force", fx.worktreeDir], { cwd: fx.repoDir });
  } catch (err) {
    errors.push(err);
  }
  try {
    const admin = new Client({
      host: pg.host,
      port: Number(pg.port),
      user: pg.user,
      password: pg.password,
      database: "postgres",
      connectionTimeoutMillis: 10_000,
      query_timeout: 10_000,
    });
    await admin.connect();
    try {
      await admin.query(`DROP DATABASE IF EXISTS ${fx.dbName} WITH (FORCE)`);
    } finally {
      await admin.end();
    }
  } catch (err) {
    errors.push(err);
  }
  try {
    rmSync(fx.scratchRoot, { recursive: true, force: true });
  } catch (err) {
    errors.push(err);
  }
  if (errors.length > 0) {
    console.error(`TRO-557 fixture cleanup had ${errors.length} failure(s):`, errors);
    throw new AggregateError(errors, `TRO-557 fixture cleanup had ${errors.length} failure(s)`);
  }
}

/** Sets up a disposable fixture, runs `fn`, and always cleans up. A cleanup
 * failure fails the test too, UNLESS `fn` itself already failed -- then the
 * original failure is what the test must report, so cleanup's own failure
 * is logged (inside cleanupFixture) rather than thrown over it. */
async function withFixture(fn: (fx: Fixture, pg: PgTarget) => Promise<void>): Promise<void> {
  const pgConn = requirePgTargetFromEnv();
  const pg: PgTarget = { ...pgConn, container: discoverPgContainer(pgConn.port) };
  const fx = makeFixture();
  let primaryError: unknown;
  try {
    await fn(fx, pg);
  } catch (err) {
    primaryError = err;
    throw err;
  } finally {
    try {
      await cleanupFixture(fx, pg);
    } catch (cleanupErr) {
      if (primaryError) {
        console.error("TRO-557 fixture cleanup ALSO failed after a test failure:", cleanupErr);
      } else {
        throw cleanupErr;
      }
    }
  }
}

describe("worktree.sh ownership stamp (TRO-557)", () => {
  it(
    "refuses a mismatched-session reuse (exit 2, database untouched); same-session retry and --steal still work",
    () =>
      withFixture(async (fx, pg) => {
        // Session A provisions the worktree for the first time.
        const first = runWorktreeSh(fx, pg, "test-session-a");
        expect(first.status, `stderr: ${first.stderr}`).toBe(0);

        const stampPath = join(fx.worktreeDir, ".factory-owner");
        expect(readFileSync(stampPath, "utf8")).toMatch(/^FACTORY_OWNER_SESSION=test-session-a$/m);

        // A marker only session A's own first provision could have created --
        // proves below whether a later call reset the database or not.
        await queryDb(pg, fx.dbName, "CREATE TABLE tro_557_marker (id int); INSERT INTO tro_557_marker VALUES (1)");

        // Session B tries to reuse the SAME ticket, without --steal.
        const second = runWorktreeSh(fx, pg, "test-session-b");
        expect(second.status).toBe(2);
        expect(second.stderr).toContain("Re-provisioning resets a database another session may be using.");
        expect(second.stderr).toContain("FACTORY_OWNER_SESSION=test-session-a");

        // The refusal must not have touched the database: the marker survives.
        const afterRefusal = await queryDb(pg, fx.dbName, "SELECT 1 FROM tro_557_marker");
        expect(afterRefusal.rowCount).toBe(1);

        // Session A's own retry is unaffected, and still resets the database
        // -- the pre-existing, load-bearing behavior this ticket must not
        // drop (brief's "Do NOT" list).
        const retry = runWorktreeSh(fx, pg, "test-session-a");
        expect(retry.status, `stderr: ${retry.stderr}`).toBe(0);
        await expect(queryDb(pg, fx.dbName, "SELECT 1 FROM tro_557_marker")).rejects.toThrow(/does not exist/);

        // Recreate the marker, then confirm --steal both proceeds AND resets
        // the database, reassigning the stamp to the stealing session.
        await queryDb(pg, fx.dbName, "CREATE TABLE tro_557_marker (id int); INSERT INTO tro_557_marker VALUES (1)");
        const steal = runWorktreeSh(fx, pg, "test-session-b", ["--steal"]);
        expect(steal.status, `stderr: ${steal.stderr}`).toBe(0);
        expect(readFileSync(stampPath, "utf8")).toMatch(/^FACTORY_OWNER_SESSION=test-session-b$/m);
        await expect(queryDb(pg, fx.dbName, "SELECT 1 FROM tro_557_marker")).rejects.toThrow(/does not exist/);
      }),
    60_000,
  );

  it(
    "treats a stamp missing FACTORY_OWNER_SESSION as an unknown owner, and refuses instead of crashing",
    () =>
      // Regression for a real bug CodeRabbit caught in this same PR: under
      // `set -euo pipefail`, grep finding no matching line exits 1, and that
      // aborted the whole script before it could reach the refusal path --
      // so a stamp from before this field existed, or a corrupted one, took
      // provisioning down instead of just refusing it.
      withFixture(async (fx, pg) => {
        const first = runWorktreeSh(fx, pg, "test-session-a");
        expect(first.status, `stderr: ${first.stderr}`).toBe(0);

        const stampPath = join(fx.worktreeDir, ".factory-owner");
        writeFileSync(stampPath, "FACTORY_OWNER_BRANCH=some-branch\n");

        const second = runWorktreeSh(fx, pg, "test-session-b");
        expect(second.status, `stderr: ${second.stderr}`).toBe(2);
        expect(second.stderr).toContain("Re-provisioning resets a database another session may be using.");
        expect(second.stderr).toContain("worktree.sh found no readable ownership stamp here.");
      }),
    60_000,
  );
});
